server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

jwt.secret=mySuperSecretKey2026UniSystemXYZ!

# IAM SERVICE
spring.cloud.gateway.routes[0].id=iam-service
spring.cloud.gateway.routes[0].uri=lb://IAM-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**,/api/students/**,/api/teachers/**

# ACADEMIC CORE
spring.cloud.gateway.routes[1].id=academic-core
spring.cloud.gateway.routes[1].uri=lb://ACADEMIC-CORE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/courses/**,/api/departments/**,/api/enrolled-courses/**

# COMMUNICATION SERVICE
spring.cloud.gateway.routes[2].id=communication-service
spring.cloud.gateway.routes[2].uri=lb://COMMUNICATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notifications/**,/api/messages/**

