server.port=8761
spring.application.name=eureka-server

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
management.health.probes.enabled=true
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka